CREATE DATABASE Softie;

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

drop table if exists Products;
CREATE TABLE Products
(
    product_id SERIAL NOT NULL,
    name character varying(50) NOT NULL,
    price real NOT NULL,
    description text NOT NULL,
    image_url character varying,
    PRIMARY KEY (product_id)
);

INSERT INTO Products (product_id, name, price, description, image_url) VALUES (1, 'Swiss Cheese', 956.97, 'Swiss cheese is a mild cow''s milk cheese with a firmer texture than baby Swiss. The flavor is light, sweet, and nutty. Swiss cheese is distinguished by its luster, pale yellow color, and large holes (called eyes) caused by carbon dioxide released during the maturation process.', 'https://i.ibb.co/N16wJ48/swiss-cheese.png');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (2, 'Pears', 759.19, 'Pears are rich in essential antioxidants, plant compounds, and dietary fiber. They pack all of these nutrients in a fat free, cholesterol free, 100 calorie package.', 'https://i.ibb.co/4fn5HJv/pear.png');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (12, 'English Muffins', 979.29, 'A small, round, yeast-leavened sourdough bread that is commonly sliced horizontally, toasted, and buttered. In North America and Australia, it is commonly eaten for breakfast, often with sweet or savory toppings such as fruit jam or honey, or eggs, sausage, bacon, or cheese.', 'https://i.ibb.co/B6pr46Z/muffins.png');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (3, 'Wasabi Paste', 669.45, 'Wasabi paste is spicy and pungent in flavour and is most commonly served with sushi and sashimi.', 'https://i.ibb.co/TB3vQy2/Wasabi-Paste.jpg');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (5, 'Triple Sec-Mcguinness', 753.58, 'When mixed with your favorite cocktail, McGuinness Triple Sec becomes three times more delicious. The drink''s name means "dry" in French, and "triple" implies three times as dry, so it''s no surprise that people fall in love with this whisky flavor.', 'https://i.ibb.co/3TVtKHm/triple.jpg');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (9, 'Apple Custard', 802.23, 'Custard apples have delicious mellow flesh that is almost as soft as custard. Custard apples are thought to have originated in South America and the West Indies. These apples are usually heart or oval in shape and can weigh up to 450g. They have quilted skin that is light tan or greenish in color and turns brown as the fruit ripens.', 'https://i.ibb.co/ctRZSqC/sugar-apple-custard-apple-sharifa-1.jpg');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (4, 'Soup - Cambells Chicken', 707.1, 'You''ll enjoy serving delicious, nutritious Campbells Chicken Noodle Soup to your children. Kids love Campbells Chicken Noodle Soup because it has bite-sized chicken, slurpable noodles, and a warm, savory broth. 12 cans weighing 10.75 oz each. Cans with a condensed flavor and an easy-to-open pop top. It''s a quick and easy way to warm up mealtime for your kids at any time.', 'https://i.ibb.co/Vp9fw0F/campbell-chicken-soup.jpg');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (6, 'Sage Ground', 936.89, 'Sage is an excellent herb for seasoning fatty meats like pork, lamb, mutton, and game (goose or duck). It also complements onions, eggplant, tomatoes, and potatoes. Sage is frequently used in stuffings and cheeses.', 'https://i.ibb.co/B65SyN5/sage-ground.jpg');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (7, 'Beef Consomme', 897.34, 'A sauce or soup base made from clarified meat stock (usually beef, veal, or poultry, but also fish) into a clear and flavorful liquid broth. Egg whites are used to clarify the meat stock as well as any additional ingredients such as vegetables and/or herbs. While the mixture is being brought to a boil, it is being stirred. The boiled solution is no longer stirred as the egg whites solidify on top of the mixture, allowing the fats and impurities to be absorbed or attached to the white.', 'https://i.ibb.co/Np4L8bs/beef-consomme.jpg');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (8, 'Sausage Chorizo', 782.82, 'Chorizo is a highly seasoned chopped or ground pork sausage that is commonly found in Spanish and Mexican cuisine. Mexican chorizo is made from fresh (raw, uncooked) pork, whereas Spanish chorizo is typically smoked.', 'https://i.ibb.co/hXsSSCt/Sausage-Chorizo.jpg');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (10, 'Bacardi Breezer', 890.29, 'The Bacardi Breezer is an excellent way to enjoy the world''s most popular rum – Bacardi. Bacardi Breezer Cranberry is a refreshing drink made from Bacardi rum, real cranberry juice, and carbonated water.', 'https://i.ibb.co/4f81wgz/bacardi.png');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (11, 'Pita Bread', 935.72, 'A versatile flat bread that is soft and slightly chewy on the inside and often has a pocket inside as a result of baking the bread in a hot oven. Pita bread is frequently mistakenly thought to be unleavened, but it is usually leavened with yeast. The bread can be eaten plain or with a drizzle of olive oil.', 'https://i.ibb.co/G21ZsqY/Original-Pita-Bread-Front-1200x1200.jpg');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (13, 'Mince - Meat FIlling', 611.56, 'Mincemeat is a combination of chopped dried fruit, distilled spirits, and spices, as well as occasionally beef suet, beef, or venison. Usually used as filling for mince pies during Christmas, but it tastes great mixed with vanilla ice cream, as well', 'https://i.ibb.co/mCMhF9N/meat-filling.jpg');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (14, 'Pate - Cognac', 787.14, 'Pâté made with pork liver and meat that has been infused with cognac. The spirits complement the pâté''s rich, smooth flavor, which is sure to appeal to foodies.', 'https://i.ibb.co/8j9ghkk/Pate-Cognac.jpg');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (15, 'Lamb Shoulder (Boneless)', 605, 'Great for roasts, stews or any lamb recipe that has a marinade or a long slow cooking time and temperature.', 'https://i.ibb.co/h9Bm7nP/lamb-shoulder.png');
INSERT INTO Products (product_id, name, price, description, image_url) VALUES (16, 'Icecream - Dark Super Cone', 867.05, 'Natural flavors, colors, and fragrances Contains no peanuts or nuts. 4 cones of French Vanilla ice cream and 4 cones of Dark Chocolate ice cream with a thick dark chocolate core These Super Cones are made with 100% Canadian dairy and are wrapped in dark chocolate sugar cones with a chocolate topping. A fantastic flavor offering in a great family package.);

